CREATE TABLE `groovatron`.`playlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

CREATE TABLE `groovatron`.`playlist_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `playlist_id` INT UNSIGNED NOT NULL REFERENCES `playlist`(id) ON DELETE CASCADE,
  `user_id` INT UNSIGNED NOT NULL REFERENCES `user`(id) ON DELETE CASCADE,
  `ownership_type` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

CREATE TABLE `groovatron`.`playlist_track` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `playlist_id` INT UNSIGNED NOT NULL REFERENCES `playlist`(id) ON DELETE CASCADE,
  `track_id` INT UNSIGNED NOT NULL REFERENCES `track`(id) ON DELETE CASCADE,
  PRIMARY KEY (`id`));

